spring:
  application:
    name: LivroDevOps

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.101.226.215:5432/livro
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true 
    hibernate:
      ddl-auto: create
  redis:
     host: 10.100.35.230
     port: 6379
     repositories:
        enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
server:
  port: 8080